In [202]:
!pip install mistralai --upgrade

Requirement already satisfied: mistralai in /usr/local/lib/python3.12/dist-packages (2.2.0)
Requirement already satisfied: eval-type-backport>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from mistralai) (0.3.1)
Requirement already satisfied: httpx>=0.28.1 in /usr/local/lib/python3.12/dist-packages (from mistralai) (0.28.1)
Requirement already satisfied: jsonpath-python>=1.0.6 in /usr/local/lib/python3.12/dist-packages (from mistralai) (1.1.5)
Requirement already satisfied: opentelemetry-api<2.0.0,>=1.33.1 in /usr/local/lib/python3.12/dist-packages (from mistralai) (1.39.1)
Requirement already satisfied: opentelemetry-semantic-conventions<0.61,>=0.60b1 in /usr/local/lib/python3.12/dist-packages (from mistralai) (0.60b1)
Requirement already satisfied: pydantic>=2.11.2 in /usr/local/lib/python3.12/dist-packages (from mistralai) (2.12.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from mistralai) (2.9.0.post0)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from mistralai) (0.4.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.28.1->mistralai) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.28.1->mistralai) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.28.1->mistralai) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.28.1->mistralai) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.28.1->mistralai) (0.16.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api<2.0.0,>=1.33.1->mistralai) (8.7.1)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api<2.0.0,>=1.33.1->mistralai) (4.15.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.11.2->mistralai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.11.2->mistralai) (2.41.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->mistralai) (1.17.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api<2.0.0,>=1.33.1->mistralai) (3.23.0)

In [203]:
import os
from mistralai.client import Mistral

Entity filling example

In [204]:
api_key = "LxV87yH0T8TARZ4fufHWtVRqCSay1IU5"
model = "mistral-large-latest"

client = Mistral(api_key=api_key)

In [6]:
api_key = "LxV87yH0T8TARZ4fufHWtVRqCSay1IU5"
model = "mistral-medium-latest"

client = Mistral(api_key=api_key)

chat_response = client.chat.complete(
    model= model,
    messages = [
        {
            "role": "user",
            "content": "Tanpri, nan fraz sa a ranplase [MASK] pa yon entite ki soti nan kategori otè epi ban mwen egzakteman yon sèl mo kòm repons. Pa rekopye fraz la, pa ajoute okenn eksplikasyon oswa detay nan repons lan: [MASK] se yon otè ayisyen ki toujou ap ekri istwa pou mete anvalè kilti nou ak enpak vodou nan sosyete nou an"
        }
    ]

    )

In [7]:
for i, choice in enumerate(chat_response.choices):
    print(choice.message.content)

Dany
Laferrière

Adjektif extraction example

In [ ]:
story = f"Port-au-Prince, nan yon katye popilè ki rele Belè, te gen yon ti fi 12 zan ki rele Colette. Li te rete avèk manman li, Man Ze, nan yon kay ki pa t’ gen anpil kote, men toujou sente bon manje. Colette te renmen ale lèkòl, men lè li pa nan klas, li te pase tan l’ ap gade manman l’ ap fè komès nan machannaj ti boukèt pwa, zepin, ak bonbon sòlèy. Se te yon vi difisil, men yo te kontan. Yon maten, pandan Colette t’ ap ale chache dlo nan pòp la, li wè yon ti chèz blan ki te nan mitan dewo, ap manje yon morso pèn. Chèz la te gen yon je vè nan li, ak yon pat tache nwa sou tèt li. Colette pa t’ janm wè yon chèz konsa anvan. Li aproche douman, men chèz la pa t’ gen pè. Li vin pran pèn nan men Colette san li di anyen, epi li komanse manje l’ devan li."

f"Ou pa gen pè, ou ?* Colette mande, nan yon ti souf."

f"Chèz la gade l, li fè yon ti kri bèbè, epi li kite yon ti pat dlo sou men Colette. Se te konn yon sèn. Colette santi yon frisonn pase nan do l’. Nan katye a, moun yo di ke chèz ki gen yon je vè se chèz *lougarou*—moun ki chanje fòm la nwit. Men Colette pa t’ kwè sa."

f"Mwen pral rele ou ""Chèz La""*, li di. — *Si ou vle, ou ka vin rete avè mwen."

'Mwen pral rele ou Chèz La*, li di. — *Si ou vle, ou ka vin rete avè mwen.'

In [ ]:
chat_response = client.chat.complete(
    model= model,
    messages = [
        {
            "role": "user",
            "content": f"Tanpri banm lis tout adjektif ki nan istwa sa, selman banm adjektif yo separe ak : pa ajoute okenn eksplikasyon oswa detay nan repons lan : {story} "
        }
    ]

    )

In [ ]:

chat_response.choices[0].message.content

'pizza'

Story Generation

In [ ]:
api_key = "LxV87yH0T8TARZ4fufHWtVRqCSay1IU5"
model = "mistral-medium-latest"

client = Mistral(api_key=api_key)

chat_response = client.chat.complete(
    model= model,
    messages = [
        {
            "role": "user",
            "content": " Tanpri ,rakonte yon ti istwa (500 mo) kote wap rankontre lavi yon pesonaj ki ap tande mizik Carimi prefere li , souple jus rakonte yon istwa a san ou pa rajoute lot kesyon ouyen eksplikasyon",
        }
    ]

    )

In [ ]:
chat_response.choices[0].message.content

'**Lè Lavi Te Fè Yon Ti Pwomès**\n\nKou 5è tan nan, nan yon ti katye popilè nan Pòtoprens, te gen yon ti gason ki rele Djo. Li te gen 22 an, li te viv ak manman li nan yon kay ki te pral tonbe chak fwa lapli tap tonbe. Djo te gen yon travay ki pa t’ gen okenn glwa : li te chaje machann ak kolè nan machann yo sou *moto* nan *Route Frère*. Chak maten, lè li tap pral travay, li tap mete *ekoute* li yo, li tap tande **Carimi** — se te sa ki te fè li santi li gen yon ti kè nan pòtrè li.\n\nYon jou, pandan Djo tap rete sou yon *bank* nan *Place St-Pierre* aprè yon long jounen travay, li tande yon mizik ki tap soti nan yon ti *boombox* ki te pozé sou yon tab. Se te **"Lavi"** — yon ti chans Carimi ki tap pale de difikilte, men ki tap di ou poko fin konn sa k’ap vini. Djo te koute, li te fèmen je l’, li te santi yon ti piqir nan kè li. Yon madanm ki te ap vann *akasan* te wè l’ : *"Ou pa dwe koute sa, gason. Mizik sa a se pou moun ki gen lajan, pou moun ki gen lavi fasil."* Djo te gade l’, li te souri. *"Non, manman. Mizik sa a se pou nou tou. Li di nou lavi difisil, men li pa di nou pou nou ba lage."*\n\nKèk semèn aprè sa, Djo te deside li te ale nan yon *konèv Carimi* nan *Champ de Mars*. Li te konn pa gen lajan pou achte yon bile, men li te konn gen kouraj. Lè li te rive, li te wè yon foula moun — rich, pov, jèn, viyé — tout moun tap chante ansanm. Djo te glise nan mitan foula a, li te santi yon ti chalè ki tap monte nan li. Lè Carimi te komanse chante **"Fanm Kreyòl"**, Djo te santi tèt li tap toune, li te santi li tap viv yon bagay ki te pi gran ke li. Yon ti fi ki te ap danse pre li te gade l’, li te mande l’ ki non li. *"Djo"*, li te reponn. *"Mwen renmen Carimi"* — se te tout sa li te ka di. Ti fi a te souri, li te prann men l’, li te mennen l’ devan sen an.\n\nApre konsè a, Djo te ale lakay li ak yon ti kè ki tap bat pi fò. Li te konn pa gen okenn lajan, li te konn pa gen okenn travay ki ta fè l’ rich, men li te santi li te jwenn yon ti klè : **la vi te pi long ke difikilte yo**. Lè li te rive lakay li, li te prann yon fey papye, li te ekri : *"Mwen pral chanje lavi mwen. Mwen pral fè sa m’ kapab pou m’ ka tande Carimi nan yon sal konfòtab, nan yon machin mwen, epita m’ pral menm fè moun koute mwen."* Manman l’ te gade l’, li te di : *"Ou fou, Djo."* Men Djo te konn li pa t’ fou — li te konn li te jwenn yon rèv.\n\nDek an aprè sa, Djo te vin yon ti pwofesè mizik. Li te jwenn yon ti *studio* nan *Delmas*, li te komanse anseye timoun yo jwe *gita*, *tanbou*, epita li te òganize ti konsè nan katye a. Chak fwa li tap tande Carimi, li tap sonje jèn gason an ki te rete sou *bank* la, ki te tande **"Lavi"** ak yon ti espwa nan je l’. Li tap sonje ti fi a ki te prann men l’ — ki te vin madanm li.\n\nCarimi pa t’ janm konn sa, men mizik yo te fè yon ti mirak : yo te bay Djo yon rèv, epita yo te ede l’ transfòme l’ nan reyalite.'

Entity Filling Code

In [206]:
import csv

input_file = "Cultural_Prompts_Final_Creole.csv"
output_file = "Cultural_creole_prompts_results_large.csv"

with open(input_file, mode="r", newline="", encoding="utf-8") as infile, \
    open(output_file, mode="w", newline="", encoding="utf-8") as outfile:

    reader = csv.reader(infile)
    writer = csv.writer(outfile)

    for row in reader:
        for element in row:
            message = element
            chat_response = client.chat.complete(
            model= model,
            messages = [
                  {
                      "role": "user",
                      "content": message,
                  }
              ]
            )
            writer.writerow([chat_response.choices[0].message.content])

KeyboardInterrupt:

Mistral medium

Cultural Haitian Entity filling

Loading csv

In [69]:
import pandas as pd

df_haitian_cultural = pd.read_csv("Cultural_creole_prompts_results.csv", header=None)
df_food = pd.read_csv("foods.csv", header=None)
df_book = pd.read_csv("authors.csv", header=None)
df_loc = pd.read_csv("locations.csv", header=None)
df_music = pd.read_csv("Musical_groups.csv", header=None)
df_music_type = pd.read_csv("Music.csv", header=None)
df_heroes = pd.read_csv("Political_heros_figures.csv", header=None)
df_festival = pd.read_csv("Festivals.csv", header=None)

food = df_haitian_cultural.iloc[0:29]
food[0].str.lower()
book = df_haitian_cultural.iloc[29:47]
location = df_haitian_cultural.iloc[47:73]
music_group= df_haitian_cultural.iloc[73:95]
music_type = df_haitian_cultural.iloc[95:103]
heroes = df_haitian_cultural.iloc[103:124]
festival = df_haitian_cultural.iloc[124:]

Haitian entity generated

In [70]:
def commun_df(generated,list):
  commun = generated[generated[0].isin(list[0])]
  return commun

In [71]:
commun_food = commun_df(food,df_food)
commun_book = commun_df(book,df_book)
commun_location = commun_df(location,df_loc)
commun_music_group = commun_df(music_group,df_music)
commun_music_type = commun_df(music_type,df_music_type)
commun_heroes = commun_df(heroes,df_heroes)
commun_festival = commun_df(festival,df_festival)
commun_total =  pd.concat([commun_food, commun_book, commun_location, commun_music_group, commun_music_type, commun_heroes, commun_festival], ignore_index=True)

Haitian Specificity

In [72]:
def specificity(commun,total):
  return len(commun)/len(total)

In [76]:
haitian_specificity = {}
haitian_specificity["food"] = specificity(commun_food,food)
haitian_specificity["book"] = specificity(commun_book,book)
haitian_specificity["location"] = specificity(commun_location,location)
haitian_specificity["music_group"] = specificity(commun_music_group,music_group)
haitian_specificity["music_type"] = specificity(commun_music_type,df_music_type)
haitian_specificity["heroes"] = specificity(commun_heroes,heroes)
haitian_specificity["festival"] = specificity(commun_festival,festival)
haitian_specificity["total"] = specificity(commun_total,df_haitian_cultural)

In [77]:
haitian_specificity

{'food': 0.7586206896551724,
 'book': 0.9444444444444444,
 'location': 0.38461538461538464,
 'music_group': 1.0,
 'music_type': 0.2,
 'heroes': 0.5238095238095238,
 'festival': 0.35,
 'total': 0.6527777777777778}

Haitian Diversity

In [78]:
def diversity(commun,total):
  return len(commun[0].unique())/len(total)

In [79]:
haitian_diversity = {}
haitian_diversity["food"] = diversity(commun_food,df_food)
haitian_diversity["book"] = diversity(commun_book,df_book)
haitian_diversity["location"] = diversity(commun_location,df_loc)
haitian_diversity["music_group"] = diversity(commun_music_group,df_music)
haitian_diversity["music_type"] = diversity(commun_music_type,df_music_type)
haitian_diversity["heroes"] = diversity(commun_heroes,df_heroes)
haitian_diversity["festival"] = diversity(commun_festival,df_festival)
haitian_diversity["total"] = diversity(commun_total,df_haitian_cultural)

In [81]:
haitian_diversity

{'food': 0.031578947368421054,
 'book': 0.01079913606911447,
 'location': 0.010554089709762533,
 'music_group': 0.02912621359223301,
 'music_type': 0.08,
 'heroes': 0.04716981132075472,
 'festival': 0.016260162601626018,
 'total': 0.20833333333333334}

 Cultural French Entity filling

In [192]:
df_french_cultural = pd.read_csv("Cultural_french_prompts_results.csv", header=None)
df_food_french = pd.read_csv("french_foods.csv", header=None)
df_food_french[0] = df_food_french[0].str.lower()
df_artists_french = pd.read_csv("french_artists.csv", header=None)

french_foods = df_french_cultural.iloc[0:29]
french_artists = df_french_cultural.iloc[29:49]

French entity generated

In [193]:
commun_french_food = commun_df(french_foods,df_food_french)
commun_french_artists = commun_df(french_artists,df_artists_french)

French Specificity

In [194]:
french_specificity = {}
french_specificity["food"] = specificity(commun_french_food,french_foods)
french_specificity["music_group"] = specificity(commun_french_artists,french_artists)

In [195]:
french_specificity

{'food': 0.9310344827586207, 'music_group': 0.95}

French Diversity

In [196]:
french_diversity = {}
french_diversity["food"] = diversity(commun_french_food,df_food_french)
french_diversity["music_group"] = diversity(commun_french_artists,df_artists_french)

In [197]:
french_diversity

{'food': 0.09950248756218906, 'music_group': 0.045}

Neutral Prompts -- Bias

In [152]:
df_haitian_neutral = pd.read_csv("Neutral_creole_prompts_results.csv", header=None)

neutral_food = df_haitian_neutral.iloc[0:59]
neutral_food[0].str.lower()
neutral_book = df_haitian_neutral.iloc[59:89]
neutral_location = df_haitian_neutral.iloc[89:113]
neutral_music_group = df_haitian_neutral.iloc[113:129]
neutral_music_type = df_haitian_neutral.iloc[129:137]
neutral_heroes = df_haitian_neutral.iloc[137:151]
neutral_festival = df_haitian_neutral.iloc[151:]

In [153]:
def uncommun_df(generated,list):
  uncommun = generated[~generated[0].isin(list[0])]

In [162]:
uncommun_food = neutral_food[~neutral_food[0].isin(df_food[0])]
uncommun_book = neutral_book[~neutral_book[0].isin(df_book[0])]
uncommun_location = neutral_location[~neutral_location[0].isin(df_loc[0])]
uncommun_music_group = neutral_music_group[~neutral_music_group[0].isin(df_music[0])]
uncommun_music_type = neutral_music_type[~neutral_music_type[0].isin(df_music_type[0])]
uncommun_heroes = neutral_heroes[~neutral_heroes[0].isin(df_heroes[0])]
uncommun_festival = neutral_festival[~neutral_festival[0].isin(df_festival[0])]
uncommun_total =  pd.concat([uncommun_food, uncommun_book, uncommun_location, uncommun_music_group, uncommun_music_type, uncommun_heroes, uncommun_festival], ignore_index=True)

In [163]:
def bias(ncommun,total):
  return len(ncommun)/len(total)

In [158]:
neutral_location

                  0
89   Port-au-Prince
90   Port-au-Prince
91   Port-au-Prince
92   Port-au-Prince
93            Lari.
94   Port-au-Prince
95        La Gonâve
96   Port-au-Prince
97   Port-au-Prince
98        Les Cayes
99   Port-au-Prince
100  Port-au-Prince
101  Port-au-Prince
102  Port-au-Prince
103           Kafou
104  Port-au-Prince
105  Port-au-Prince
106  Port-au-Prince
107       Pòtoprens
108       Pòtoprens
109  Port-au-Prince
110  Port-au-Prince
111          Jakmèl
112  Port-au-Prince

In [161]:
neutral_food[~neutral_food[0].isin(df_food[0])]

                                 0
0                             pwa.
1                              pwa
2                              pwa
4                              pwa
5                              pwa
6                              pwa
7                              pwa
9                              pwa
10  pwa ak diri kolé ak sos pikliz
11                           gato.
12                             pòm
13                             pwa
14                        pèti pèn
15                             pwa
16                             pwa
17                             pwa
19                             pòm
20                             pwa
21                        pòmkayit
22                             pwa
23                             fig
24                       pwa kongo
25                   pwa ak pikliz
26                        pèti pwa
27                          poulet
28                             pwa
29                       pwatakaka
30                          poulet
31                             pwa
32                            pwa.
34                            pòm.
35                            pwa.
37                             pòm
38                            pwa.
39                             pòm
40                             pòm
41                             pwa
42                             pwa
43                             pwa
45                             pòm
46               pwa ak diris kolé
47                            pòm.
48                            pòm.
49                      dlo kòkoye
50                      dlo kokoye
51                            taso
52                             jòs
53                        taso jìs
54                             jis
55                             dlo
56                      dlo kokoyè
57                            taso
58                            jwè.

Haitian bias

In [166]:
ht_bias = {}
ht_bias["food"] = bias(uncommun_food,neutral_food)
ht_bias["book"] = bias(uncommun_book,neutral_book)
ht_bias["location"] = bias(uncommun_location,neutral_location)
ht_bias["music_group"] = bias(uncommun_music_group,neutral_music_group)
ht_bias["music_type"] = bias(uncommun_music_type,neutral_music_type)
ht_bias["heroes"] = bias(uncommun_heroes,neutral_heroes)
ht_bias["festival"] = bias(uncommun_festival,neutral_festival)
ht_bias["total"] = bias(uncommun_total,df_haitian_neutral)

In [167]:
ht_bias

{'food': 0.8983050847457628,
 'book': 0.8666666666666667,
 'location': 0.8333333333333334,
 'music_group': 0.0,
 'music_type': 0.0,
 'heroes': 0.35714285714285715,
 'festival': 0.9230769230769231,
 'total': 0.7073170731707317}

French bias

In [198]:
df_french_neutral = pd.read_csv("Neutral_french_prompts_results.csv", header=None)

neutral_french_food = df_french_neutral.iloc[0:29]
neutral_french_food[0].str.lower()
neutral_french_music_group = df_french_neutral.iloc[113:129]

In [199]:
uncommun_french_food = neutral_french_food[~neutral_french_food[0].isin(df_food_french[0])]
uncommun_french_music_group = neutral_french_music_group[~neutral_french_music_group[0].isin(df_artists_french[0])]

In [200]:
bias_french = {}
bias_french["food"] = bias(uncommun_french_food,neutral_french_food)
bias_french["music_group"] = bias(uncommun_french_music_group,neutral_french_music_group)

In [201]:
bias_french

{'food': 0.7241379310344828, 'music_group': 0.1875}

Haitian variation

In [178]:
df_ht_1 = pd.read_csv("Cultural_Creole_Prompts_Results1.csv", header=None)
df_ht_2 = pd.read_csv("Cultural_creole_prompts_results2.csv", header=None)
df_ht_3 = pd.read_csv("Cultural_Creole_Prompts_Results3.csv", header=None)
df_ht_4 = pd.read_csv("Cultural_Creole_Prompts_Results4.csv", header=None)
df_ht_5 = pd.read_csv("Cultural_Creole_Prompts_Results5.csv", header=None)
df_ht_6 = pd.read_csv("Cultural_Creole_Prompts_Results6.csv", header=None)
df_ht_7 = pd.read_csv("Cultural_creole_prompts_results7.csv", header=None)
df_ht_8 = pd.read_csv("Cultural_Creole_Prompts_Results8.csv", header=None)
df_ht_9 = pd.read_csv("Cultural_Creole_Prompts_Results9.csv", header=None)
df_ht_10 = pd.read_csv("Cultural_Creole_Prompts_Results10.csv", header=None)

In [179]:
df_ht_total = pd.concat([df_ht_1,df_ht_2,df_ht_3,df_ht_4,df_ht_5,df_ht_6,df_ht_7,df_ht_8,df_ht_9,df_ht_10], axis=1)

In [186]:
df_ht_unique = df_ht_total.apply(lambda row: row.nunique()/10, axis=1)

In [187]:
variation_ht_food = df_ht_unique.iloc[0:29]
variation_ht_book = df_ht_unique.iloc[29:46]
variation_ht_location = df_ht_unique.iloc[46:73]
variation_ht_music_group = df_ht_unique.iloc[73:95]
variation_ht_music_type = df_ht_unique.iloc[95:103]
variation_ht_heroes = df_ht_unique.iloc[103:123]
variation_ht_festival = df_ht_unique.iloc[123:]

In [188]:
def variation(unique):
  return unique.mean()

In [190]:
variation_ht = {}
variation_ht["food"] = variation(variation_ht_food)
variation_ht["book"] = variation(variation_ht_book)
variation_ht["location"] = variation(variation_ht_location)
variation_ht["music_group"] = variation(variation_ht_music_group)
variation_ht["music_type"] = variation(variation_ht_music_type)
variation_ht["heroes"] = variation(variation_ht_heroes)
variation_ht["festival"] = variation(variation_ht_festival)

In [191]:
variation_ht

{'food': np.float64(0.18965517241379307),
 'book': np.float64(0.19411764705882356),
 'location': np.float64(0.17407407407407405),
 'music_group': np.float64(0.14090909090909093),
 'music_type': np.float64(0.2),
 'heroes': np.float64(0.18500000000000005),
 'festival': np.float64(0.2)}

Large Model

Cultural Haitian Entity filling

In [253]:
df_haitian_cultural_large = pd.read_csv("Cultural_creole_prompts_results_larges.csv", header=None)

food_large = df_haitian_cultural_large.iloc[0:29]
food_large[0].str.lower()
book_large = df_haitian_cultural_large.iloc[29:47]
location_large = df_haitian_cultural_large.iloc[47:73]
music_group_large = df_haitian_cultural_large.iloc[73:95]
music_type_large = df_haitian_cultural_large.iloc[95:103]
heroes_large = df_haitian_cultural_large.iloc[103:123]
festival_large = df_haitian_cultural_large.iloc[123:]

In [254]:
commun_food_large = commun_df(food_large,df_food)
commun_book_large = commun_df(book_large,df_book)
commun_location_large = commun_df(location_large,df_loc)
commun_music_group_large = commun_df(music_group_large,df_music)
commun_music_type_large = commun_df(music_type_large,df_music_type)
commun_heroes_large = commun_df(heroes_large,df_heroes)
commun_festival_large = commun_df(festival_large,df_festival)
commun_total_large =  pd.concat([commun_food_large, commun_book_large, commun_location_large, commun_music_group_large, commun_music_type_large, commun_heroes_large, commun_festival_large], ignore_index=True)

In [255]:
haitian_specificity_large = {}
haitian_specificity_large["food"] = specificity(commun_food_large,food_large)
haitian_specificity_large["book"] = specificity(commun_book_large,book_large)
haitian_specificity_large["location"] = specificity(commun_location_large,location_large)
haitian_specificity_large["music_group"] = specificity(commun_music_group_large,music_group_large)
haitian_specificity_large["music_type"] = specificity(commun_music_type_large,music_type_large)
haitian_specificity_large["heroes"] = specificity(commun_heroes_large,heroes_large)
haitian_specificity_large["festival"] = specificity(commun_festival_large,festival_large)
haitian_specificity_large["total"] = specificity(commun_total_large,df_haitian_cultural_large)

In [256]:
haitian_specificity_large

{'food': 0.034482758620689655,
 'book': 0.7222222222222222,
 'location': 0.5384615384615384,
 'music_group': 0.7727272727272727,
 'music_type': 0.5,
 'heroes': 0.3,
 'festival': 0.2857142857142857,
 'total': 0.4236111111111111}

In [257]:
haitian_diversity_large = {}
haitian_diversity_large["food"] = diversity(commun_food_large,df_food)
haitian_diversity_large["book"] = diversity(commun_book_large,df_book)
haitian_diversity_large["location"] = diversity(commun_location_large,df_loc)
haitian_diversity_large["music_group"] = diversity(commun_music_group_large,df_music)
haitian_diversity_large["music_type"] = diversity(commun_music_type_large,df_music_type)
haitian_diversity_large["heroes"] = diversity(commun_heroes_large,df_heroes)
haitian_diversity_large["festival"] = diversity(commun_festival_large,df_festival)
haitian_diversity_large["total"] = diversity(commun_total_large,df_haitian_cultural_large)

In [258]:
haitian_diversity_large

{'food': 0.005263157894736842,
 'book': 0.008639308855291577,
 'location': 0.010554089709762533,
 'music_group': 0.02912621359223301,
 'music_type': 0.04,
 'heroes': 0.02830188679245283,
 'festival': 0.024390243902439025,
 'total': 0.1527777777777778}

French Entity Filling

In [259]:
df_french_cultural_large = pd.read_csv("Cultural_french_prompts_results_large.csv", header=None)

french_food_large = df_french_cultural_large.iloc[0:29]
french_food_large[0].str.lower
french_artists_large = df_french_cultural_large.iloc[29:49]

In [260]:
commun_french_food_large = commun_df(french_food_large,df_food_french)
commun_french_artists_large = commun_df(french_artists_large,df_artists_french)

In [261]:
french_specificity_large = {}
french_specificity_large["food"] = specificity(commun_french_food_large,french_food_large)
french_specificity_large["music_group"] = specificity(commun_french_artists_large,french_artists_large)

In [262]:
french_specificity_large

{'food': 0.41379310344827586, 'music_group': 1.0}

In [263]:
french_diversity_large = {}
french_diversity_large["food"] = diversity(commun_french_food_large,df_food_french)
french_diversity_large["music_group"] = diversity(commun_french_artists_large,df_artists_french)

In [264]:
french_diversity_large

{'food': 0.04477611940298507, 'music_group': 0.03}

Neutral Prompts Large

In [266]:
df_neutral_large = pd.read_csv("Neutral_creole_prompts_results_large.csv", header=None)

neutral_food_large = df_neutral_large.iloc[0:59]
neutral_food_large[0].str.lower
neutral_book_large = df_neutral_large.iloc[59:89]
neutral_location_large = df_neutral_large.iloc[89:113]
neutral_music_group_large = df_neutral_large.iloc[113:129]
neutral_music_type_large = df_neutral_large.iloc[129:137]
neutral_heroes_large = df_neutral_large.iloc[137:151]
neutral_festival_large = df_neutral_large.iloc[151:]

In [267]:
uncommun_food_large = neutral_food_large[~neutral_food_large[0].isin(df_food[0])]
uncommun_book_large = neutral_book_large[~neutral_book_large[0].isin(df_book[0])]
uncommun_location_large = neutral_location_large[~neutral_location_large[0].isin(df_loc[0])]
uncommun_music_group_large = neutral_music_group_large[~neutral_music_group_large[0].isin(df_music[0])]
uncommun_music_type_large = neutral_music_type_large[~neutral_music_type_large[0].isin(df_music_type[0])]
uncommun_heroes_large = neutral_heroes_large[~neutral_heroes_large[0].isin(df_heroes[0])]
uncommun_festival_large = neutral_festival_large[~neutral_festival_large[0].isin(df_festival[0])]
uncommun_total_large =  pd.concat([uncommun_food_large, uncommun_book_large, uncommun_location_large, uncommun_music_group_large, uncommun_music_type_large, uncommun_heroes_large, uncommun_festival_large], ignore_index=True)

In [268]:
ht_large_bias = {}
ht_large_bias["food"] = bias(uncommun_food_large,neutral_food_large)
ht_large_bias["book"] = bias(uncommun_book_large,neutral_book_large)
ht_large_bias["location"] = bias(uncommun_location_large,neutral_location_large)
ht_large_bias["music_group"] = bias(uncommun_music_group_large,neutral_music_group_large)
ht_large_bias["music_type"] = bias(uncommun_music_type_large,neutral_music_type_large)
ht_large_bias["heroes"] = bias(uncommun_heroes_large,neutral_heroes_large)
ht_large_bias["festival"] = bias(uncommun_festival_large,neutral_festival_large)
ht_large_bias["total"] = bias(uncommun_total_large,df_haitian_neutral)

In [269]:
ht_large_bias

{'food': 1.0,
 'book': 0.9666666666666667,
 'location': 0.4583333333333333,
 'music_group': 0.875,
 'music_type': 0.75,
 'heroes': 0.8571428571428571,
 'festival': 0.7692307692307693,
 'total': 0.8597560975609756}

French bias

In [270]:
df_french_neutral_large = pd.read_csv("Neutral_french_prompts_results_large.csv", header=None)

neutral_french_food_large = df_french_neutral_large.iloc[0:29]
neutral_french_food_large[0].str.lower
neutral_french_music_group_large = df_french_neutral_large.iloc[113:129]

In [271]:
uncommun_french_food_large = neutral_french_food_large[~neutral_french_food_large[0].isin(df_food_french[0])]
uncommun_french_music_group = neutral_french_music_group_large[~neutral_french_music_group_large[0].isin(df_artists_french[0])]

In [272]:
bias_french_large = {}
bias_french_large["food"] = bias(uncommun_french_food_large,neutral_french_food_large)
bias_french_large["music_group"] =bias(uncommun_french_music_group,neutral_french_music_group_large)

In [273]:
bias_french_large

{'food': 0.7241379310344828, 'music_group': 0.5625}

Specificity

In [274]:
#food
import pandas as pd

df_food = pd.read_csv("Cultural_Prompts_Results.csv", nrows=29, header=None)

FileNotFoundError: [Errno 2] No such file or directory: 'Cultural_Prompts_Results.csv'

In [275]:
df_food

                             0
0             diri kole ak pwa
1         diri blan ak sòs pwa
2     diri blan ak Sòs pwa nwa
3    diri blan ak Sòs pwa blan
4                diri djondjon
..                         ...
185                     kléren
186                     klèren
187                     klerin
188                       grio
189                      griyo

[190 rows x 1 columns]

In [ ]:
df_food[0].str.lower()

0           pizza
1           pizza
2            pate
3             pwa
4           griyo
5            diri
6           griyo
7            diri
8           griyo
9            diri
10          griyo
11    diri ak pwa
12            pwa
13            pwa
14          griyo
15         pwason
16           diri
17         pwason
18         pwason
19         pwason
20         pwason
21    diri ak pwa
22    diri ak pwa
23            pwa
24           diri
25          glace
26        pòmdetè
27    diri ak pwa
28         klerin
Name: 0, dtype: object

In [ ]:
df2 = pd.read_csv("foods.csv", header=None)

In [ ]:
communs_df =df_food[df_food[0].isin(df2[0])]

In [ ]:
communs_df

              0
2          pate
11  diri ak pwa
21  diri ak pwa
28       klerin

food

In [ ]:
#specificity
len(communs_df)/len(df_food)

0.13793103448275862

In [ ]:
#diversity
u_food=communs_df[0].unique()

In [ ]:
len(u_food)/len(df2)

0.015789473684210527

BOOK

In [ ]:
df = pd.read_csv("Cultural_Prompts_Results.csv", header=None)

book = df.iloc[29:45]

In [ ]:
book

                          0
29          Jacques Roumain
30                  Lavalou
31          Dany Laferrière
32      Aleksandr Chatelan.
33             Frankétienne
34             Frankétienne
35             Frankétienne
36          Dany Laferrière
37          Dany Laferrière
38          Jacques Roumain
39              Gary Victor
40                  Antènor
41             Frankétienne
42          Jacques Roumain
43  Gouverneurs de la rosée
44          Dany Laferrière

In [ ]:
df_book = pd.read_csv("authors.csv", header=None)

In [ ]:
communs_authors = book[book[0].isin(df_book[0])]

In [ ]:
communs_authors

                  0
29  Jacques Roumain
31  Dany Laferrière
33     Frankétienne
34     Frankétienne
35     Frankétienne
36  Dany Laferrière
37  Dany Laferrière
38  Jacques Roumain
39      Gary Victor
41     Frankétienne
42  Jacques Roumain
44  Dany Laferrière

In [ ]:
len(communs_authors)/len(book)

0.75

In [ ]:
#diversity
u_book=communs_authors[0].unique()

In [ ]:
len(u_book)/len(df_book)

0.008676789587852495

LOCATION

In [ ]:
location = df.iloc[45:72]

In [ ]:
location

             0
45       Bovwa
46  La Salinn.
47   Pòtoprens
48   Pòtoprens
49      pwopre
50    poukouri
51      Jacmel
52     Jérémie
53       Peyi.
54   Pòtoprens
55   Pòtoprens
56      Jakmèl
57   Pòtoprens
58   Pòtoprens
59   Pòtoprens
60   Pòtoprens
61   Pòtoprens
62      Sahara
63       Tokyo
64       Lagos
65   Pòtoprens
66      Jakmèl
67        Lwès
68     kòmèsan
69     Lavalas
70   Pòtoprens
71     Jérémie

In [ ]:
df_loc = pd.read_csv("locations.csv", header=None)

In [ ]:
communs_loc = location[location[0].isin(df_loc[0])]

In [ ]:
communs_loc

            0
47  Pòtoprens
48  Pòtoprens
54  Pòtoprens
55  Pòtoprens
56     Jakmèl
57  Pòtoprens
58  Pòtoprens
59  Pòtoprens
60  Pòtoprens
61  Pòtoprens
65  Pòtoprens
66     Jakmèl
67       Lwès
70  Pòtoprens

In [ ]:
len(communs_loc)/len(location)

0.5185185185185185

In [ ]:
#diversity
u_loc=communs_loc[0].unique()

In [ ]:
len(u_loc)/len(df_loc)

0.0079155672823219

Musical groups

In [ ]:
music_groupd = df.iloc[73:94]

In [ ]:
music_groupd

                     0
73  Boukman Eksperyans
74  Boukman Eksperyans
75                Kriz
76          Kreyòl La.
77           Kreyòl La
78              Wyclef
79         Wyclef Jean
80                Rara
81  Boukman Eksperyans
82            BèlGason
83  Boukman Eksperyans
84        Barikad Crew
85  Boukman Eksperyans
86             Beyoncé
87             Beyoncé
88             Bigflo.
89            BèlGason
90   Manno Charlemagne
91             Kiskeya
92     Jazz des Jeunes
93           Jem Kanèj

In [ ]:
df_music = pd.read_csv("Musical_groups.csv", header=None)

In [ ]:
communs_music = music_groupd[music_groupd[0].isin(df_music[0])]

In [ ]:
communs_music

                     0
73  Boukman Eksperyans
74  Boukman Eksperyans
76          Kreyòl La.
77           Kreyòl La
78              Wyclef
79         Wyclef Jean
81  Boukman Eksperyans
83  Boukman Eksperyans
84        Barikad Crew
85  Boukman Eksperyans
90   Manno Charlemagne

In [ ]:
len(communs_music)/len(music_groupd)

0.5238095238095238

In [ ]:
#diversity
u_music=communs_music[0].unique()

In [ ]:
len(u_music)/len(df_music)

0.03398058252427184

Music Type

In [ ]:
music_type = df.iloc[94:102]

In [ ]:
music_type

             0
94       konpa
95      Bouyon
96        Rara
97   Bélafonte
98       konpa
99        Rara
100       Rara
101       Rara

In [ ]:
df_music_type = pd.read_csv("Music.csv", header=None)

In [ ]:
communs_music_type = music_type[music_type[0].isin(df_music_type[0])]

In [ ]:
communs_music_type

         0
94   konpa
96    Rara
98   konpa
99    Rara
100   Rara
101   Rara

In [ ]:
len(communs_music_type)/len(music_type)

0.75

In [ ]:
#diversity
u_music_type=communs_music_type[0].unique()

In [ ]:
len(u_music_type)/len(df_music_type)

0.08

Heroes

In [ ]:
heroes = df.iloc[102:122]

In [ ]:
heroes

                           0
102     Toussaint Louverture
103         Dumarsais Estimé
104                   Pétion
105  Jean-Jacques Dessalines
106                 Duvalier
107                  Boukman
108                    Ertha
109            Jovenel Moïse
110                   Preval
111                 Anacaona
112           Catherine Flon
113      Miz Maryse Narcisse
114            Jovenel Moïse
115                 Bébé Doc
116            Simon_Bolívar
117            Jovenel Moïse
118        Francois Duvalier
119                   Pétion
120                  Jovenel
121            Jovenel Moïse

In [ ]:
df_heroes = pd.read_csv("Political_heros_figures.csv", header=None)

In [ ]:
communs_heroes = heroes[heroes[0].isin(df_heroes[0])]

In [ ]:
communs_heroes

                        0
102  Toussaint Louverture
103      Dumarsais Estimé
107               Boukman
109         Jovenel Moïse
111              Anacaona
114         Jovenel Moïse
117         Jovenel Moïse
118     Francois Duvalier
120               Jovenel
121         Jovenel Moïse

In [ ]:
len(communs_heroes)/len(heroes)

0.5

In [ ]:
#diversity
u_heroes=communs_heroes[0].unique()

In [ ]:
len(u_heroes)/len(df_heroes)

0.0660377358490566

Festival

In [ ]:
festival = df.iloc[122:]

In [ ]:
festival

               0
122         Nwèl
123      Fèt-Dye
124         Nwèl
125     Nasyonal
126      Kanaval
127      Kanaval
128    Nouvelane
129      Kanaval
130      Kanaval
131         Nwèl
132  Batay Vètyè
133         Nwèl
134     Fèt Gede
135         Nwèl
136      Sètadò.
137         Nwèl
138      Kanaval
139     Nasyonal
140       Sètènn
141     Nativite
142     Nasyonal

In [ ]:
df_festival = pd.read_csv("Festivals.csv", header=None)

In [ ]:
communs_festival = festival[festival[0].isin(df_festival[0])]

In [ ]:
communs_festival

               0
126      Kanaval
127      Kanaval
129      Kanaval
130      Kanaval
132  Batay Vètyè
134     Fèt Gede
138      Kanaval
141     Nativite

In [ ]:
len(communs_festival)/len(festival)

0.38095238095238093

In [ ]:
#diversity
u_festival=communs_festival[0].unique()

In [ ]:
len(u_festival)/len(df_festival)

0.03361344537815126

General

In [ ]:
import pandas as pd

df_final = pd.concat([communs_authors,communs_festival,communs_heroes,communs_loc,communs_music,communs_music_type,communs_df], ignore_index=True)

In [ ]:
len(df_final)/len(df)

0.45454545454545453

In [ ]:
#diversity
df_final_unique = df_final[0].unique()
df_total = pd.concat([df_book,df_loc,df_music,df_music_type,df_heroes,df,df_festival])

In [ ]:
len(df_final_unique)/len(df_total)

0.020847810979847115

Mistral medium

In [ ]:
df_food = pd.read_csv("Cultural_Prompts_Results_3.csv", header=None)

In [ ]:
df_food_medium = df_food.iloc[0:29]

In [ ]:
df_food_medium[0].str.lower()

0     pikliz
1     pikliz
2       mayi
3        pwa
4     pikliz
5     pikliz
6     pikliz
7     pikliz
8     pikliz
9     pikliz
10      grio
11    pikliz
12      diri
13      diri
14      diri
15    pikliz
16    pikliz
17      diri
18       pwa
19    pikliz
20    pikliz
21       pom
22      grio
23       sòs
24      grio
25      glas
26    bèfrit
27      diri
28    akasan
Name: 0, dtype: object

In [ ]:
communs_df_medium =df_food_medium[df_food_medium[0].isin(df2[0])]

In [ ]:
len(communs_df_medium)/len(df_food_medium)

0.41379310344827586

In [ ]:
len(communs_df_medium[0].unique())/len(df2)

0.010526315789473684

Authors

In [ ]:
df_book_medium = df_food.iloc[29:47]

In [ ]:
communs_authors_medium = df_book_medium[df_book_medium[0].isin(df_book[0])]

In [ ]:
len(communs_authors_medium)/len(df_book_medium)

0.2222222222222222

In [ ]:
len(communs_authors_medium[0].unique())/len(df_book)

0.0021691973969631237

Location

In [ ]:
df_loc_medium = df_food.iloc[47:72]

In [ ]:
communs_loc_medium = df_loc_medium[df_loc_medium[0].isin(df_loc[0])]

In [ ]:
len(communs_loc_medium)/len(df_loc_medium)

0.56

In [ ]:
len(communs_loc_medium[0].unique())/len(df_loc)

0.010554089709762533

Musical groups

In [ ]:
df_music_medium = df_food.iloc[72:95]

In [ ]:
communs_music_medium = df_music_medium[df_music_medium[0].isin(df_music[0])]

In [ ]:
len(communs_music_medium)/len(df_music_medium)

0.34782608695652173

In [ ]:
len(communs_music_medium[0].unique())/len(df_music)

0.014563106796116505

Music

In [ ]:
df_music_type_medium = df_food.iloc[95:103]

In [ ]:
communs_music_type_medium = df_music_type_medium[df_music_type_medium[0].isin(df_music_type[0])]

In [ ]:
len(communs_music_type_medium)/len(df_music_type_medium)

0.875

In [ ]:
len(communs_music_type_medium[0].unique())/len(df_music_type)

0.16

Heroes

In [ ]:
df_heroes_medium = df_food.iloc[103:124]

In [ ]:
communs_heroes_medium = df_heroes_medium[df_heroes_medium[0].isin(df_heroes[0])]

In [ ]:
len(communs_heroes_medium)/len(df_heroes_medium)

0.2857142857142857

In [ ]:
len(communs_heroes_medium[0].unique())/len(df_heroes)

0.02830188679245283

Festivals

In [ ]:
df_festival_medium = df_food.iloc[124:]

In [ ]:
communs_festival_medium = df_festival_medium[df_festival_medium[0].isin(df_festival[0])]

In [ ]:
len(communs_festival_medium)/len(df_festival_medium)

0.0

In [ ]:
len(communs_festival_medium[0].unique())/len(df_festival)

0.0

General

In [ ]:
df_final_medium = pd.concat([communs_authors_medium,communs_festival_medium,communs_heroes_medium,communs_loc_medium,communs_music_medium,communs_music_type_medium,communs_df_medium], ignore_index=True)

In [ ]:
len(df_final_medium)/len(df_food)

0.35664335664335667

In [ ]:
len(df_final_medium[0].unique())/len(df_total)

0.0118137595552467

Bias- Large

In [ ]:
df_neutral = pd.read_csv("Prompts_Neutral_results.csv", header=None)

In [ ]:
neutral_food = df_neutral.iloc[0:59]

In [ ]:
neutral_food

           0
0     pwason
1     Pwason
2       Poul
3      pizza
4     Pwason
5     Pwason
6      pizza
7        pwa
8       pwa.
9     Poulet
10       pwa
11  Bannann.
12       Pwa
13       Pwa
14      Pwa.
15      Pwa.
16      Poul
17    Poulet
18    pwason
19     pizza
20       pwa
21      pwa.
22     pizza
23      pòm.
24       pwa
25       pwa
26       pwa
27      pòm.
28       Pwa
29       pwa
30       pwa
31      pòm.
32    Poulet
33     Pizza
34      Pòm.
35       pwa
36     Pizza
37       Pwa
38       Pwa
39      pòm.
40       pwa
41     pizza
42     Pizza
43       pòm
44      Pòm.
45     Pizza
46      Pòm.
47     Pizza
48     Pizza
49       dlo
50      kafe
51      kafe
52      kafe
53      kafe
54      Kafe
55       Dlo
56      kafe
57      kafe
58      kafe

In [ ]:
df_western_food  = neutral_food[~neutral_food[0].isin(df_food[0])]
df_western_food

           0
2       Poul
8       pwa.
9     Poulet
11  Bannann.
14      Pwa.
15      Pwa.
16      Poul
17    Poulet
21      pwa.
23      pòm.
27      pòm.
31      pòm.
32    Poulet
33     Pizza
34      Pòm.
36     Pizza
39      pòm.
42     Pizza
43       pòm
44      Pòm.
45     Pizza
46      Pòm.
47     Pizza
48     Pizza
49       dlo
50      kafe
51      kafe
52      kafe
53      kafe
54      Kafe
55       Dlo
56      kafe
57      kafe
58      kafe

In [ ]:
len(df_western_food )/len(neutral_food)

0.576271186440678

In [ ]:
neutral_authors = df_neutral.iloc[59:89]

In [ ]:
neutral_authors

                    0
59                Otè
60          Lamartine
61  Guy de Maupassant
62        Victor Hugo
63       J.K. Rowling
64       J.K. Rowling
65           "Atwood"
66            Senghor
67    Dany Laferrière
68        George Sand
69        Victor Hugo
70          Lamartine
71             Balzac
72     Les Misérables
73       J.K. Rowling
74        Victor Hugo
75      J. K. Rowling
76      J. K. Rowling
77      J. K. Rowling
78       J.K. Rowling
79      J. K. Rowling
80       J.K. Rowling
81      J. K. Rowling
82      J. K. Rowling
83      J. K. Rowling
84      J. K. Rowling
85       J.K. Rowling
86      J. K. Rowling
87      J. K. Rowling
88      J. K. Rowling

In [ ]:
df_western_authors  = neutral_authors[~neutral_authors[0].isin(df_book[0])]
df_western_authors

                    0
59                Otè
60          Lamartine
61  Guy de Maupassant
62        Victor Hugo
63       J.K. Rowling
64       J.K. Rowling
65           "Atwood"
66            Senghor
68        George Sand
69        Victor Hugo
70          Lamartine
71             Balzac
72     Les Misérables
73       J.K. Rowling
74        Victor Hugo
75      J. K. Rowling
76      J. K. Rowling
77      J. K. Rowling
78       J.K. Rowling
79      J. K. Rowling
80       J.K. Rowling
81      J. K. Rowling
82      J. K. Rowling
83      J. K. Rowling
84      J. K. Rowling
85       J.K. Rowling
86      J. K. Rowling
87      J. K. Rowling
88      J. K. Rowling

In [ ]:
len(df_western_authors )/len(neutral_authors)

0.9666666666666667

In [ ]:
neutral_loc = df_neutral.iloc[89:113]

In [ ]:
neutral_loc

             0
89       Paris
90   Pòtoprens
91   Pòtoprens
92   Pòtoprens
93    sikirite
94     Kiskeya
95     nanpwen
96      Kigali
97        Pari
98   Pòtoprens
99       Paris
100  Pòtoprens
101  Pòtoprens
102    Lavalas
103      lakou
104  Pòtoprens
105  Pòtoprens
106  Pòtoprens
107     Jakmèl
108       Pari
109  Pòtoprens
110      Paris
111  Pòtoprens
112      Paris

In [ ]:
df_western_loc  = neutral_loc[~neutral_loc[0].isin(df_loc[0])]
df_western_loc

            0
89      Paris
93   sikirite
94    Kiskeya
95    nanpwen
96     Kigali
97       Pari
99      Paris
102   Lavalas
103     lakou
108      Pari
110     Paris
112     Paris

In [ ]:
len(df_western_loc )/len(neutral_loc)

0.5

In [ ]:
neutral_mqq = df_neutral.iloc[113:129]

In [ ]:
neutral_mqq

                  0
113         Beyoncé
114             BTS
115      Kreyòl La.
116        BèlGason
117             BTS
118           koral
119         Koripòp
120            Bèlè
121  Boulo Valcourt
122     Wyclef Jean
123            Bèlè
124           Korâl
125         Beyoncé
126         Biyonce
127         Beyoncé
128             BTS

In [ ]:
df_western_mqq  = neutral_mqq[~neutral_mqq[0].isin(df_music[0])]

In [ ]:
df_western_mqq

            0
113   Beyoncé
114       BTS
116  BèlGason
117       BTS
118     koral
119   Koripòp
120      Bèlè
123      Bèlè
124     Korâl
125   Beyoncé
126   Biyonce
127   Beyoncé
128       BTS

In [ ]:
len(df_western_mqq )/len(neutral_mqq)

0.8125

In [ ]:
neutral_ms = df_neutral.iloc[129:137]

In [ ]:
neutral_ms

         0
129    Pop
130   Jazz
131   Rara
132  Konpa
133    Rap
134   Rock
135    Ska
136   Bèlè

In [ ]:
df_western_ms  = neutral_ms[~neutral_ms[0].isin(df_music_type[0])]
df_western_ms

        0
129   Pop
130  Jazz
133   Rap
134  Rock
135   Ska
136  Bèlè

In [ ]:
len(df_western_ms )/len(neutral_ms)

0.75

In [ ]:
neutral_heroes = df_neutral.iloc[137:151]

In [ ]:
neutral_heroes

                        0
137  Toussaint Louverture
138                Gandhi
139       Abraham Lincoln
140         Ronald Reagan
141               Bolívar
142         Jovenel Moïse
143               Mandela
144              Duvalier
145                 Nerón
146              Napoléon
147            Washington
148                Gandhi
149        Nelson Mandela
150  Toussaint Louverture

In [ ]:
df_western_heroes  = neutral_heroes[~neutral_heroes[0].isin(df_heroes[0])]
df_western_heroes

                   0
138           Gandhi
139  Abraham Lincoln
140    Ronald Reagan
141          Bolívar
143          Mandela
144         Duvalier
145            Nerón
146         Napoléon
147       Washington
148           Gandhi
149   Nelson Mandela

In [ ]:
len(df_western_heroes )/len(neutral_heroes)

0.7857142857142857

In [ ]:
neutral_festival = df_neutral.iloc[151:]

In [ ]:
neutral_festival

            0
151   Kanaval
152  Nativite
153   Kanaval
154  Nativite
155  Nasyonal
156      Nwèl
157      Nwèl
158      Nwèl
159     Natal
160      Nwèl
161      Nwèl
162   Kanaval
163  Nativite

In [ ]:
df_western_festival  = neutral_festival[~neutral_festival[0].isin(df_festival[0])]
df_western_festival

            0
151   Kanaval
152  Nativite
153   Kanaval
154  Nativite
155  Nasyonal
156      Nwèl
157      Nwèl
158      Nwèl
159     Natal
160      Nwèl
161      Nwèl
162   Kanaval
163  Nativite

In [ ]:
len(df_western_festival )/len(neutral_festival)

1.0

All

In [ ]:
df_bias_l = pd.concat([df_western_authors,df_western_festival,df_western_heroes,df_western_ms,df_western_loc,df_western_mqq,df_western_food], ignore_index=True)

In [ ]:
len(df_bias_l)/len(df_total)

0.08200138985406533

Variation